# Site settings
title: "Michael W. Merriam's Academic and Professional Resume"
description: "See Title"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Michael W. Merriam"
resume_title:                   "Independent"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "michael@ludoception.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "917-455-1420"
resume_contact_address:         "45 Academy Ave, Pittsburgh, PA, 15228"

resume_header_contact_info:     "917-455-1420 â€¢ michael@ludoception.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I study the ways in which literature, particularly in the form of Game Writing (as a sub-discipline of Creative Writing), encroaches on and redefines areas historically treated as the domain of coding and game design. This necessarily means I also study code as literature, and games as literary events, and/or artifacts, within the Humanities. My research centers on the intersection of game writing and game design, particularly where methods of quest structure, game balance, and quantitative difficulty, could inform pedagogy (but typically don't).<p>Methodologically, I combine practice-led prototyping with critical analysis of player communities, both in my professional life as a Narrative Designer, and in my research. I look at how players interpret rules as stories, and stories as rules, and how narrative authority can be shared between designers (or teachers) and players (or students), and how creative writing in games extends into computational domains. In pedagogy, I build curricula where the classroom operates first as a design space, then as an interdependent game world. Students test mechanics and prose in tandem, and assessment is structured around iteration, playtest documentation, and collaborative design. My broader aim is to develop frameworks that help writers think in systems and designers use narrative techniques, supporting both literary education and game studies research."

# resume_header_intro: "<p>My research and professional interests involve the overlap of Game Writing and Game Design, specifically the ways that Creative Writing can re-define the boundaries of what counts as Game Design. This has lately involved the concept of Game Balance, which is an area less often touched on in studies of game narratives, but which could provide narrative writers a way to address directly more quantitative and computational elements of design. (Put more simply, at what point does Game Writing become indistinguishable from Game Design?)<p>I specialize in curriculum innovation through game dynamics. With a core skill set that includes instructional design, educational technology integration, and game theory, I create immersive learning experiences.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank

resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mwmxyz/academic"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/michael-merriam1/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://www.ludoception.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
